language: go
go:
  - 1.8.x

before_install:
  - go get honnef.co/go/tools/cmd/megacheck

script:
  - make

before_deploy:
  - gem install fpm package_cloud
  - make release-build deb release-package

deploy:
  provider: releases
  api_key:
    secure: cnVQOSmxZwrsUtddpw9pxgDzf7B4jtUCfSdartHrFl8SyQsP3anQEOgC0TYbVbV1PLl3k2MAVpbSr6otVs66GcYFLD5BlrpHgN5aKh4TrBRq9IrCaG5FFoX9KhulLqFAOgHAz9YCnjMeO8iR9d2v1wQADTr+wHzPE4e1zJyc2QxEAC1ZPtjBq+gH/wR1gw3lAP7aQeYokBvdB4eEmJFWnBqnUdu1rrJZDPrFzAaLAD/DhOLyXYCJGW+9c1kLwUmHdgXqFeTS1dIxyFCWQhqNJ//Vn8THpChmNKD4KhGTUnTSQVoOyaMqIqktPgWH9KxnM3F8BKDRer4NavLpwXym66bd7VIUJ7cWO7uv13Yd0uI4lWbnt2nYVi7dYGSFxvRLFnTz8brnI+tuQ958dzRGhNR9H5GDjpugKUGn3DYMLuqfVQS74zQk2c4v0JngP1LNKBrT/lNHH8RFnHhjyCke8V2URSkBphXVeMZrGRmqXBUXES5tAoGJ/xoUZhO2R5voNKuQXoojLtHc5SCmYjB84JpGnPutZgzVrs/nj2FDVZCK891uQI6pURVpBrMbFCVun1KY58jG5uH5SQ+iTmNMX2MeGTzCgvsd4W8ewG+EuYb/h77RxbqhoDxIjvaoo3Rdhj3vlFY09T15tQ9DYlAx1/T6/goYAuAlrHMx5Y2rytE=
  file:
    - build/ipmi_exporter_darwin_amd64
    - build/ipmi_exporter_freebsd_386
    - build/ipmi_exporter_freebsd_amd64
    - build/ipmi_exporter_linux_386
    - build/ipmi_exporter_linux_amd64
    - build/ipmi_exporter_linux_arm
    - build/ipmi_exporter_linux_arm64
    - build/ipmi_exporter_windows_386.exe
    - build/ipmi_exporter_windows_amd64.exe
  on:
    repo: lovoo/ipmi_exporter
    tags: true
